### ISSUE TITLE
안녕하세요 ~ !! 이슈사항 전달해 드립니다.

### ISSUE THREAD

**Issue by ninace** [recomio/howabout-android#15]
김태호님  안녕하세요 ~^^ 
먼저, 이렇게 센스있는 코딩을 오픈해 주셔서 감사드립니다.

다름아니라, 이슈사항이 발생해 전달하고자 합니다. 
이슈사항은 How About 프로젝트 import후에 실행했을때 아래와 같은 현상이 발생합니다.

W/nalizableReferenceQueue(31561): Could not load Finalizer in its own class loader.
 Loading Finalizer in the current class loader instead. 
As a result, you will not be able to garbage collect this class loader.
To support reclaiming this class loader, either resolve the underlying issue, 
or move Google Collections to your system class path.

W/nalizableReferenceQueue(31561):
java.io.FileNotFoundException: com/google/inject/internal/util/$Finalizer.class

초반에 파일을 찾을수 없다는 FileNotFoundException:이 뜨면서,
음악 정보 데이터를 받아오지 못하는거 같아, 실질적 동작을 하지 못하고 있습니다.

한번 살펴봐 주셨으면 합니다.

**Comment by xissy** [comment]
안녕하세요. 이 HowAbout 앱에서 추천API로 사용하고 있던 recom.io 서비스가 피인수 되면서 더 이상 추천 서비스를 일반에 제공하지 않고 있습니다. 때문에 이 앱도 동작하지 않게 되었습니다. 먼저 공지하지 못해 죄송합니다. 감사합니다.
